canonical: http://hl7.org/cda/us/ccda
fhirVersion: 5.0.0
FSHOnly: true
applyExtensionMetadataToRoot: false
# id: hl7.cda.us.ccda
# name: CCDA
# status: draft
version: "2.1"
dependencies:
  hl7.cda.uv.core:
    version: current
    uri: http://hl7.org/cda/stds/core/ImplementationGuide/hl7.cda.uv.core
    id: cda
  us.nlm.vsac:
    version: 0.15.0
    uri: http://fhir.org/packages/us.nlm.vsac/ImplementationGuide/us.nlm.vsac
    id: vsac
  us.cdc.phinvads:
    version: 0.12.0
    uri: http://fhir.org/packages/us.cdc.phinvads/ImplementationGuide/us.cdc.phinvads
    id: phinvads
  hl7.fhir.us.core:
    version: current
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore
  hl7.fhir.uv.tools:
    version: current
    uri: http://hl7.org/fhir/tools/ImplementationGuide/hl7.fhir.uv.tools
    id: tools
